# Generated by Django 3.2.7 on 2026-07-29 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=125)),
                ('Age', models.IntegerField()),
                ('Licence', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Location', models.CharField(max_length=150)),
                ('Joining', models.DateField(auto_now_add=True)),
                ('Users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=150)),
                ('Weight', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=250)),
                ('Message', models.CharField(max_length=250)),
                ('Rating', models.IntegerField(choices=[(1, '⭐ Poor'), (2, '⭐⭐ Fair'), (3, '⭐⭐⭐ Good'), (4, '⭐⭐⭐⭐ Very Good'), (5, '⭐⭐⭐⭐⭐ Excellent')])),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('Gen', models.CharField(max_length=15)),
                ('Img', models.ImageField(upload_to='media/')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Pass', models.CharField(max_length=120)),
                ('Cpass', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=150)),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasagency.cylinder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasagency.register')),
            ],
        ),
        migrations.CreateModel(
            name='AssignAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasagency.agents')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasagency.booking')),
            ],
        ),
    ]
