# Generated by Django 3.2.7 on 2026-07-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasagency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinder',
            old_name='Quantity',
            new_name='Available',
        ),
        migrations.RenameField(
            model_name='cylinder',
            old_name='Weight',
            new_name='Net',
        ),
    ]
