# Generated by Django 3.2.7 on 2026-07-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasagency', '0002_auto_20260729_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='Users',
            new_name='user',
        ),
    ]
