# Generated by Django 3.2.7 on 2026-08-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasagency', '0003_rename_users_agents_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gasagency.register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agents',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
